using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace TypeModeling.Analyzers.ValueObject;

/// <summary>値オブジェクト記述からの UTF8 source 出力</summary>
internal static class ValueObjectSourceEmitter
{
    /// <summary>値オブジェクト生成結果の出力</summary>
    /// <param name="context">source 生成 context</param>
    /// <param name="description">値オブジェクトの生成記述</param>
    internal static void Produce(
        SourceProductionContext context,
        ValueObjectDescription description)
    {
        if (description.Diagnostic is not null)
        {
            context.ReportDiagnostic(Diagnostic.Create(
                description.Diagnostic,
                description.Location,
                description.MessageArguments));
            return;
        }

        if (description.Model is null)
            return;

        var model = description.Model;
        var toString = model.UnderlyingIsValueType
            ? "public override string ToString() => Value.ToString();"
            : "public override string ToString() => Value?.ToString() ?? string.Empty;";

        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated/>");
        builder.AppendLine("#nullable enable");
        builder.AppendLine("using TypeModeling.Domain;");
        builder.AppendLine();

        if (model.Namespace is not null)
        {
            builder.AppendLine($"namespace {model.Namespace};");
            builder.AppendLine();
        }

        builder.AppendLine($"partial record {model.TypeName}");
        builder.AppendLine("{");
        builder.AppendLine("    /// <summary>検証を経た基底値</summary>");
        builder.AppendLine($"    public {model.Underlying} Value {{ get; }}");
        builder.AppendLine();
        builder.AppendLine("    /// <summary>検証済みの基底値による値オブジェクトの内部構築</summary>");
        builder.AppendLine("    /// <param name=\"value\">検証済みの基底値</param>");
        builder.AppendLine($"    private {model.TypeName}({model.Underlying} value) => Value = value;");
        builder.AppendLine();
        builder.AppendLine("    /// <summary>外部表現の検証を経た値オブジェクトの構築</summary>");
        builder.AppendLine("    /// <param name=\"raw\">検証していない外部表現</param>");
        builder.AppendLine("    /// <returns>検証に成功した値オブジェクトまたは検証の理由を持つ失敗</returns>");
        builder.AppendLine($"    public static Result<{model.TypeName}, {model.Failure}> Create({model.Underlying} raw) => Parse(raw).Map(value => new {model.TypeName}(value));");
        builder.AppendLine();
        builder.AppendLine("    /// <summary>基底値の文字列表現</summary>");
        builder.AppendLine("    /// <returns>基底値の文字列表現</returns>");
        builder.AppendLine($"    {toString}");
        builder.AppendLine("}");

        context.AddSource(
            $"{model.TypeName}.ValueObject.g.cs",
            SourceText.From(builder.ToString(), Encoding.UTF8));
    }
}
